app/blueprints/document_types/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for

from .services import (
    create_document_type_service,
    delete_document_type_service,
    get_all_document_types,
    get_document_type,
    update_document_type_service,
)

doc_types_bp = Blueprint("doc_types", __name__, url_prefix="/doc_types")


# == HOME ==
@doc_types_bp.route("/")
def home():
    success, message, document_types = get_all_document_types()

    if not success:
        flash(message, "error_doc_types_home")

    return render_template("doc_types/home.html", document_types=document_types)


# == REGISTRAR DOCUMENTO ==
@doc_types_bp.route("/new")
def new_document_type():
    return render_template("doc_types/new_document_type.html")


@doc_types_bp.route("/create", methods=["POST"])
def create_document_type():
    if request.method == "POST":
        doc_type_name = request.form.get("doc_type_name")
        success, message, _ = create_document_type_service(doc_type_name)

        if success:
            flash(message, "success_doc_types_new_document_type")
        else:
            flash(message, "error_doc_types_new_document_type")

    return redirect(url_for("doc_types.new_document_type"))


# == EDITAR DOCUMENTO ==
@doc_types_bp.route("/edit/<int:doc_type_id>")
def edit_document_type(doc_type_id):
    success, message, document = get_document_type(doc_type_id)

    if not success:
        flash(message, "error_doc_types_edit_document_type")

    return render_template("doc_types/edit_document_type.html", document=document)


@doc_types_bp.route("/update", methods=["POST"])
def update_document_type():
    if request.method == "POST":
        doc_type_id = request.form.get("doc_type_id")
        doc_type_name = request.form.get("doc_type_name")

        success, message, _ = update_document_type_service(doc_type_id, doc_type_name)

        if success:
            flash(message, "success_doc_types_edit_document_type")
        else:
            flash(message, "error_doc_types_edit_document_type")

        return redirect(
            url_for("doc_types.edit_document_type", doc_type_id=doc_type_id)
        )

    return redirect(url_for("doc_type.home"))


# == ELIMINAR DOCUMENTO ==
@doc_types_bp.route("/delete/<int:document_type_id>")
def delete_document_type(document_type_id):
    success, message = delete_document_type_service(document_type_id)

    if success:
        flash(message, "success_doc_types_home")
    else:
        flash(message, "error_doc_types_home")

    return redirect(url_for("doc_types.home"))

app/templates/doc_types/edit_document_type.html
{% extends "base.html" %}

<!-- MENSAJES FLASH -->
{% set flash_categories = {
'error_doc_types_edit_document_type': 'alert-danger',
'success_doc_types_edit_document_type': 'alert-success'
} %}

{% block title %}Editar | Tipo de documento{% endblock %}

{% block body %}

<!-- HEADER -->
{% include "headers/main_header.html" %}

<div class="container mt-5">
    <!-- TÍTULO -->
    <h1 class="mb-4 text-primary text-center">Editar tipo de documento</h1>

    {% if document %}
    <!-- CARD CON FORMULARIO -->
    <div class="card shadow-sm rounded-3 mx-auto" style="max-width: 700px;">
        <div class="card-body">
            <form action="{{ url_for('doc_types.update_document_type') }}" method="post">
                <input type="hidden" name="doc_type_id" value="{{ document.id }}">

                <!-- INPUT -->
                <div class="mb-3">
                    <label for="doc_type_name" class="form-label fw-bold">Nombre</label>
                    <input type="text" name="doc_type_name" id="doc_type_name" class="form-control"
                        value="{{ document.name }}" maxlength="50" required>
                </div>

                <!-- BOTONES -->
                <div class="d-flex justify-content-between">
                    <a href="{{ url_for('doc_types.home') }}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-save"></i> Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

app/templates/doc_types/home.html
{% extends "base.html" %}

<!-- MENSAJES FLASH -->
{% set flash_categories = {
'error_doc_types_home': 'alert-danger',
'success_doc_types_home': 'alert-success'
} %}

{% block title %}Tipos de documento{% endblock %}

{% block body %}

<!-- HEADER -->
{% include "headers/main_header.html" %}

<div class="container mt-5">
    <!-- TÍTULO -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="text-primary">Tipos de documento</h1>
        <a href="{{ url_for('doc_types.new_document_type') }}" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Registrar
        </a>
    </div>

    <!-- TABLA -->
    {% if document_types %}
    <div class="card shadow-sm rounded-3">
        <div class="card-body p-0">
            <table class="table table-hover mb-0">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col" class="text-center">Editar</th>
                        <th scope="col" class="text-center">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for document in document_types %}
                    <tr>
                        <td>{{ document.name }}</td>
                        <td class="text-center">
                            <a href="{{ url_for('doc_types.edit_document_type', doc_type_id=document.id) }}"
                                class="btn btn-sm btn-outline-primary">
                                <i class="bi bi-pen-fill"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                                data-bs-target="#confirmDeleteModal"
                                data-message="¿Seguro que deseas eliminar el tipo de documento <strong>{{ document.name}}</strong>?"
                                data-url="{{ url_for('doc_types.delete_document_type', document_type_id=document.id) }}">
                                <i class="bi bi-trash3-fill"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <!-- ALERTA SI NO HAY REGISTROS -->
    <div class="alert alert-warning text-center mt-4" role="alert">
        No hay tipos de documento registrados.
    </div>
    {% endif %}
</div>

{% endblock %}

app/templates/doc_types/new_document_type.html
{% extends "base.html" %}

{% set flash_categories = {
'error_doc_types_new_document_type': 'alert-danger',
'success_doc_types_new_document_type': 'alert-success'
} %}

{% block title %}Registrar | Tipo de documento{% endblock %}

{% block body %}

{% include "headers/main_header.html" %}

<div class="container mt-5">

    <!-- TÍTULO -->
    <h1 class="mb-4 text-center text-primary">Registrar tipo de documento</h1>

    <!-- FORMULARIO -->
    <div class="card shadow-sm rounded-3 mx-auto" style="max-width: 700px;">
        <div class="card-body">
            <form action="{{ url_for('doc_types.create_document_type') }}" method="post">
                <!-- Nombre -->
                <div class="mb-3">
                    <label for="doc_type_name" class="form-label fw-bold">Nombre</label>
                    <input type="text" name="doc_type_name" id="doc_type_name" class="form-control" maxlength="50"
                        placeholder="Ejemplo: Cédula, Pasaporte..." required>
                </div>

                <div class="d-flex justify-content-between">
                    <a href="{{url_for('doc_types.home')}}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-save"></i> Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}